### ISSUE TITLE
Couple of changes I had to make

### ISSUE THREAD

**Issue by jeff-h** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#1]
Thanks for sharing this! I tried using the vanilla approach and it worked, but with no sound or iGPU acceleration. Using your EFI everything works much better (other than sleep)! Also I just upgraded to Big Sur 11.5.2 without a hitch.

I'm running this on a 600 G1 with the i5-4590 @ 3.3 using the HD4600 iGPU, and the EFI from this repo didn't work out-of-the box; in case it helps anyone else, I did have the following two issues:

1. On first reboot I got the "configuration requires vault but no vault provided" error. The fix is to change `Vault` to `Optional` as per https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#stuck-on-no-vault-provided
2. After this it stalled during startup with the line `LOG:EXITBS:START`. This is documented at https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start The fix that worked for me was to set `AppleXcpmCfgLock` to `Yes`.

@1alessandro1 — assuming your G1 is a stock i5 like mine, I'm confused how your EFI works for you without the above changes. It seems to be the way with Hackintoshing, but I still don't understand why.

**Comment by 1alessandro1** [comment]
Hi, thank you for reporting your experience, I'll explain here why I had those options in my config.plist:

- `Vault` set to `Secure`: this helps me ensuring that no tampering is made to any file in my EFI folder, but in order to be coherent with that option, one must copy his EFI folder inside the `OpenCore-0.7.3-RELEASE/` next to the other folders like `X64`, `Utilities`, etc and then open a terminal, go to `Utilities/CreateVault` and then type the following command:

```
xattr -cr RsaTool; ./sign.command
```

This is also recommended in the configuration.pdf from acidanthera, and while it has no functional benefits other than ensuring that every file is fine (with its SHA-256 calculated at every boot) it is helpful for me to ensure everything is okay.

- `LOG:EXITBS:START` is due to a BIOS setting that you should unlock, without using the patch `AppleXcpmCfgLock`, since that can cause instability and kernel panics after some hours of use: the BIOS setting to be unlocked is called `CFG-Lock` which in your firmware is currently set to `Enabled`, so macOS kernel cannot write to the `MSR 0xE2` register for correct power management, and fail to boot. However, there are few methods to unlock it even though it is not present alongside the standard BIOS options, and in the readme I should have provided the correct offsets already, since we have the same motherboard... since I've seen that you are one of those who reads documentation (and trust me that is an exception which is rare nowadays) I recommend to follow [this](https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#checking-if-your-firmware-supports-cfg-lock-unlocking) guide to disable the setting and disable the write protection. It's not necessary to follow the section where you extract the BIOS, since you can find the [Setup.txt](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/blob/main/Bios-Dumps/Section_Freeform_subtype_GUID_97E409E6-4CC1-11D9-81F6-000000000000_Setup_Setup_body.txt) file (read the dortania guide and you'll know what this file is for) in my repository and continue from there in the guide, these are the `setup_var` commands I recommend to follow:

[Source: from the readme I wrote](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS#additional-hidden-bios-settings)

- CFG Lock: `setup_var 0x4A3 0x00` [Disabled]
- DVMT GFX total mem: `setup_var 0x234 0x3` [MAX]
- VT-d Support: `setup_var 0x238 0x00` [Disabled]
- EHCI Hand-off: `setup_var 0x2 0x1` [Enabled]
- Wake on LAN: `setup_var 0x85 0x0` [Disabled]
- Serial ports: [Disable All]
  - (Serial Port A) `setup_var 0x13 0x00`
  - (Serial Port B) `setup_var 0x15 0x00`
  - (Serial Port C) `setup_var 0x17 0x00`
  - (Serial Port D) `setup_var 0x19 0x00`

If you want you can skip the VT-d check, since that can be replaced with the harmless `DisableIoMapper` kernel patch, and can help you to use intel IOMMU on other systems such as QUBES or Proxmox (if you're KVM geek)

**Comment by jeff-h** [comment]
Thanks for such a detailed response. I totally forgot that I did not implement your BIOS settings fully. My HP still has a much earlier BIOS than yours and it seems you need Windows to update it, so I forged ahead without it for now.

I've definitely got some homework to do now!

**Comment by 1alessandro1** [comment]
> My HP still has a much earlier BIOS than yours and it seems you need Windows to update it

Nope, this is not necessary... Just prepare a DOS usb any windows pc with [Rufus](https://www.thomas-krenn.com/en/wiki/Creating_a_Bootable_DOS_USB_Stick) already installed and copy [this](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/tree/main/Bios-Dumps/DOS%20Flash) folder inside and execute:

```
DOSFlash.exe
```

**Comment by jeff-h** [comment]
I actually don't have access to a Windows machine at all, but managed to create a bootable FreeDOS USB drive using [these instructions](http://www.techiesparks.com/2014/07/09/make-bootable-usbsd-card-mac-os-x/891) (had no luck with UNetbootin sadly) on my Mac. After that I succeeded in updating the BIOS to 2.78! 🎉 Thanks for your help.

After that I had a lot of trouble working out how to get the HP to boot using the datasone GRUB, but I think that's just because I don't have much experience with PCs. Eventually I got it going, and ran all the BIOS config commands from your documentation. Another success! 🎉

I then modified my `config.plist` to disable `AppleXcpmCfgLock` as it was originally in your version. I decided to leave `Vault` set to `Optional`... hope that's not a problem.

Unfortunately though, for me all of the above achieved... nothing lol Everything still works that worked before, but the one thing that wasn't working (crash after waking from sleep) is still happening :(

I've noticed it's not sleep nor wake that crashes, as the system is fine for usually about 5 seconds or so after wake. But presumably the system is trying to wake something and crashing after that short period after waking. I also noticed that the fan doesn't spin down during sleep, so I'm not sure it's really sleeping properly.

Anyway, you have gone above and beyond already with your help, so thanks again! I would definitely not have gotten this far without your instructions.

**Comment by 1alessandro1** [comment]
> (crash after waking from sleep) is still happening 

Maybe it depends on some particular peripheral you're using, try to swap them and see if anything changes. I've tested sleep/wake cycles multiple times with previous OpenCore versions and macOS versions, all of them work perfectly, as you can see from this screenshot

![image](https://user-images.githubusercontent.com/46293832/137494604-6513343d-175e-4e5c-80b0-bf9d1eef7f2c.png)


Report back if you discover anything

**Comment by jeff-h** [comment]
Well that's weird :) I just tried sleep again (selecting sleep from the Apple menu) and it went to "sleep" and woke up just fine. I have about six hard drives plugged in, as well as a Focusrite audio interface and several other usb devices, so there's plenty to go wrong.

I use quotes around "sleep" as the fan never stops on the G1, and the external drives don't seem to stop spinning. The G1 and external hard drives are using about 30–40 W in this state, which is not fantastic, but really not too bad.

Thanks for the `pmset` command above! I hadn't come across it. It was quite interesting, firstly throwing a lot similar to:

```
2021-10-20 19:43:59 +1300 Assertions          	PID 186(coreaudiod) Released PreventUserIdleDisplaySleep "com.apple.audio.context167.preventuseridledisplaysleep" 121:06:46 id:0x0x5000082b7 [System: DeclUser NetAcc kCPU kDisp]
```

Quitting Logic Pro seems to have fixed that. Now I get: 

```
2021-10-20 20:01:01 +1300 Sleep               	Entering DarkWake state due to 'Software Sleep pid=179': Using AC (Charge:0%)
2021-10-20 20:01:01 +1300 Assertions          	PID 88(powerd) Created InternalPreventSleep "com.apple.powermanagement.darkwakelinger" 00:00:00  id:0x0xd000084a2 [System: DeclUser SRPrevSleep NetAcc kCPU kDisp]
2021-10-20 20:01:14 +1300 Assertions          	PID 88(powerd) TimedOut InternalPreventSleep "com.apple.powermanagement.darkwakelinger" 00:00:13  id:0x0xd000084a2 [System: DeclUser SRPrevSleep NetAcc kCPU kDisp]
```

It seems I'm getting "DarkWake" not sleep, which probably isn't surprising since I have all the HDs shared (using macOS file sharing) and I also have a Virtualbox VM running. I think DarkWake would be expected even on a real Mac with all that running. At some point I'll try it again with all that stopped and report back.

All in all I'd call that a win :) Thanks again for your expert advice getting me to this point!
