### ISSUE TITLE
System restarts when I click my bootable Mojave USB

### ISSUE THREAD

**Issue by parsapaknahad** [1alessandro1/HP-Prodesk-600-G1-SFF-macOS#5]
Hi,
First of all, Thank you for this work.
I did every step of your guide, but then when I click on my Mojave bootable USB on CLI OC menu, the system restarts.
I am look forward to your help.
Here is my config.plist.
Thanks.
[config.zip](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/files/8251349/config.zip)

**Comment by 1alessandro1** [comment]
Hi @P4RS44, since you're booting an older version of macOS, you should adjust your config.plist to match the APFS.efi driver version for Mojave, currently my config.plist allows to boot only macOS versions above Big Sur 11.0.1 

![image](https://user-images.githubusercontent.com/46293832/158401709-7855e125-77ec-4108-8a4c-523672e3263d.png)


Try this one below, it has OpenCore 0.7.9 which I will update when I can on master.
[EFI.zip](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/files/8254371/EFI.zip)

**Comment by parsapaknahad** [comment]
> Hi @P4RS44, since you're booting an older version of macOS, you should adjust your config.plist to match the APFS.efi driver version for Mojave, currently my config.plist allows to boot only macOS versions above Big Sur 11.0.1
> 
> ![image](https://user-images.githubusercontent.com/46293832/158401709-7855e125-77ec-4108-8a4c-523672e3263d.png)
> 
> Try this one below, it has OpenCore 0.7.9 which I will update when I can on master. [EFI.zip](https://github.com/1alessandro1/HP-Prodesk-600-G1-SFF-macOS/files/8254371/EFI.zip)

Thank you for your response.
I tried your EFI, but it still restarts after selecting Mojave USB.

**Comment by 1alessandro1** [comment]
Then you did not apply the correct BIOS settings or downloaded a corrupted Mojave image

Not an issue with this repository
